<?php
defined('BASEPATH') or exit('No direct script access allowed');
init_public_head();
?>
<div class="section-height-800 breadcrumb-vision context-dark text-center">
	<div class="shell section-bottom-30">
		<div class="veil reveal-md-block">
			<h1 class="text-bold" style="color: cornsilk;">Vision &amp; Mission</h1>
		</div>
		<ul class="list-inline list-inline-with-arrows p">
			<ul class="list-inline list-inline-with-arrows p">
				<li><a href="<?php echo base_url() ?>" class="text-white">Home </a></li>
				<li style="color: cornsilk;">Vision &amp; Mission</li>
			</ul>
		</ul>
	</div>
</div>
<section class="section-90 section-md-top-120 section-md-bottom-111">
	<div class="shell-fluid">
		<div class="range range-xs-center range-md-left text-left">
			<div class="cell-xs-10 cell-sm-8 cell-md-7 offset-top-60 offset-md-top-0">

				<h3 class="inset-left-30"><strong>Vision</strong></h3><br />
				<ul class="inset-left-10 list list-marked">
					<div class="inset-md-left-30 offset-top-10">
						<li>
							<p align="justify">Started by Rao Bahadur <strong>Shri.A.Veeriya Vandayar</strong> and his illustrious brother <strong>Shri.A.Krishnaswamy Vandayar</strong> of Poondi with a far-sighted vision of educating the rural masses, the motto of the College is <strong>"to learn and to serve"</strong>. The Secretary and Correspondent of the college, <strong>Shri.K.Thulasiah Vandayar</strong> has a vision to offer quality academic programmes and value oriented higher education to the rural community in Tamilnadu to equip them to meet the challenges of time in terms of regional, national and global demands with moral standards and quality.
						</li>
						</p>
					</div>
				</ul>
			</div>
			<div class="cell-xs-10 cell-sm-8 cell-md-5"><img alt="" class="img-responsive" height="400" src="<?php echo base_url('assets/images/vision.jpg') ?>" width="720" /></div>
		</div>
	</div>
</section>
<section class="section-md-bottom-111">
	<div class="shell-fluid">
		<div class="range range-xs-center range-md-left  text-left">
			<div class="cell-xs-10 cell-sm-8 cell-md-5"><img alt="" class="img-responsive" height="400" src="<?php echo base_url('assets/images/mission.jpg') ?>" width="720" /></div>
			<div class="cell-xs-10 cell-sm-8 cell-md-7 offset-top-60 offset-md-top-0">

				<h3 class="inset-left-30"><strong>Mission</strong></h3><br />
				<ul class="inset-left-10 list list-marked">
					<div class="inset-md-left-30  offset-top-10">
						<li>
							<p align="justify">The Mission of <strong>A.V.V.M. Sri Pushpam College (Autonomous)</strong> is to build leadership qualities, competent minds and form compassionate hearts. The college imparts a practical, demanding and overall development of the personality generated by love, consideration and care for society.</p><br>
						</li>
						<li>
							<p align="justify">The college offers a wide range of needs, interests and programmes within a challenging, supportive and conducive environment for the clear vision of the future and to apply it for the betterment of the nation.</p><br>
						</li>
						<li>
							<p align="justify">The Vision and Mission is reflected in the trust document of the college that declares to serve and empower the downtrodden people of this rural agrarian backward area in the fields of Education, Technology and Agriculture.</p><br>
						</li>
					</div>
				</ul>
			</div>
		</div>
	</div>
</section>
<?php
init_public_tail();
?>